### ISSUE TITLE
problem with gulp watch

### ISSUE THREAD

**Issue by Nesrine86** [ivandoric/d8theming#7]
I need help please 
I have this error when I save changes :
$ gulp watch
[11:34:38] Using gulpfile C:\wamp64\www\drupal-8.8.4\gulpfile.js
[11:34:39] Starting 'watch'...
[11:34:54] Starting 'sass'...
[11:34:55] Starting '<anonymous>'...
[11:34:55] function done() {
    d.removeListener('error', onError);
    d.exit();
    return tryCatch(cb, arguments);
  } reloaded.

I have gulp 4.0.2
My gulpfile.js :

var gulp = require('gulp');
var livereload = require('gulp-livereload')
var uglify = require('gulp-uglifyjs');
var sass = require('gulp-sass');
var autoprefixer = require('gulp-autoprefixer');
var sourcemaps = require('gulp-sourcemaps');
var imagemin = require('gulp-imagemin');
var pngquant = require('imagemin-pngquant');

gulp.task('imagemin', function () {

    return gulp.src('./themes/custom/mytheme/images/*')
        .pipe(imagemin({
            progressive: true,
            svgoPlugins: [{removeViewBox: false}],
            use: [pngquant()]
        }))
        .pipe(gulp.dest('./themes/custom/mytheme/images'));
});

gulp.task('sass', function () {
  gulp.src('./themes/custom/mytheme/sass/**/*.scss')
    .pipe(sourcemaps.init())
        .pipe(sass({outputStyle: 'compressed'}).on('error', sass.logError))
        .pipe(autoprefixer('last 2 version', 'safari 5', 'ie 7', 'ie 8', 'ie 9', 'opera 12.1', 'ios 6', 'android 4'))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./themes/custom/mytheme/css'));
});

gulp.task('uglify', function() {
  gulp.src('./themes/custom/mytheme/lib/*.js')
    .pipe(uglify('main.js'))
    .pipe(gulp.dest('./themes/custom/mytheme/js'))
});

gulp.task('watch', function(){
    livereload.listen();

    gulp.watch('./themes/custom/mytheme/sass/**/*.scss',  gulp.series('sass'));
    gulp.watch('./themes/custom/mytheme/lib/*.js',  gulp.series('uglify'));
    gulp.watch(['./themes/custom/mytheme/css/style.css', './themes/custom/mytheme/**/*.twig', './themes/custom/mytheme/js/*.js'], function (files){
        livereload.changed(files)
    });
});

**Comment by ivandoric** [comment]
It could be Windows issue, it could be that you are probably using gulpfile from the series and I'm not sure if this kind of configuration is still valid in Gulp 4.0 ... I would suggest asking at some Gulp forum about it, since I'm not the expert.
